### ISSUE TITLE
Upgrade for Keystone 4.0

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/generator-keystone#222] opened 2016-10-14 08:40 UTC
Please upgrade the Yeoman generator to handle the latest Keystone 4.0

**Comment by jay-at-avido** [comment] 2016-10-17 15:45
+1.

In the meantime, it would be nice to at least know if it can be used to install 4.x on top of it.
Here's some unconfirmed advice I have been given on Gitter:

> Ben Stokoe @benstokoe
Easiest way is use the yeoman generator, then npm uninstall keystone and the npm install keystone@next

**Comment by VinayaSathyanarayana** [comment] 2016-10-17 18:31
Yeoman generator installs the old version. Need documentation on how to install the latest version.

**Comment by VinayaSathyanarayana** [comment] 2016-10-18 17:37
@JedWatson - Your Inputs please

**Comment by mxstbr** [comment] 2016-10-18 18:01
We will be comprehensively reworking the generator for the version four release.

As posted above, the easiest way right now is:

```
npm install -g generator-keystone
yo keystone
npm uninstall keystone
npm install keystone@next
```

**Comment by josephdburdick** [comment] 2016-10-22 19:42
I followed these steps but run into an error anyway. ```
/Users/jb/Sites/js/node/apps/diaz-gill/keystone.js:77
keystone.Email.defaults.templateExt = 'hbs';
                                    ^

TypeError: Cannot set property 'templateExt' of undefined
    at Object.<anonymous> (/Users/jb/Sites/js/node/apps/diaz-gill/keystone.js:77:37)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```
Should I manually upgrade the internals by referring to https://github.com/keystonejs/generator-keystone/pull/128 ?

**Comment by mxstbr** [comment] 2016-10-22 19:51
No, `keystone.Email` is now a separate package, [`keystone-email`](http://npm.im/keystone-email). You can remove that entire block of code from your `keystone.js` file!

**Comment by josephdburdick** [comment] 2016-10-22 19:57
Thanks @mxstbr the install is running now (and thank you for all of your open source contributions). Is there any estimated timeline on when the React version of everything will be out? I'm wondering if I can use this on an upcoming project.

**Comment by mxstbr** [comment] 2016-10-23 06:40
> Is there any estimated timeline on when the React version of everything will be out?

No, sorry 😢 We've gotten really busy with real work recently, so haven't been able to do as much as we want to.

**Comment by VinayaSathyanarayana** [comment] 2016-11-10 12:13
Any progress on this?

**Comment by rph28** [comment] 2016-11-19 02:05
Does anyone get this error?

```
npm i keystone@next --save
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/Rob/.nvm/versions/node/v6.9.1/bin/node" "/Users/Rob/.nvm/versions/node/v6.9.1/bin/npm" "i" "keystone@next" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install keystone as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Rob/Library/Mobile Documents/com~apple~CloudDocs/Coder Factory Academy/javascript/boiler_plates/keystone/npm-debug.log
```

**Comment by VinayaSathyanarayana** [comment] 2017-01-08 16:37
Any progress on this - Now that the Beta is nearly stable

**Comment by JedWatson** [comment] 2017-02-16 00:44
We've merged the initial work for this, it'll be released soon. We're delaying the more significant work @mxstbr mentioned for the sake of a release 😄 

Going to close this because the master branch now pulls in 4.0

**Closed by JedWatson** 2017-02-16 00:44 UTC

**Comment by VinayaSathyanarayana** [comment] 2017-02-23 14:24
What is the best way to install Keystone 4.0 now?

**Comment by Noviny** [comment] 2017-02-23 23:54
@VinayaSathyanarayana There was just a bit more tidying to do before we were happy doing a new npm launch. If you want to use the generator with Keystone 4 now, you can run

```
npm install -g generator-keystone@keystonejs/generator-keystone
```

to install from master. I'd recommend upgrading again as soon as we get our next npm release though.

Otherwise, you can still follow the uninstall/reinstall instructions above.

The biggest chunk missing from master is that the email setup needs to be redone.

**Comment by nervous-energy** [comment] 2017-03-05 11:00
I love Keystone.js, but if I had to offer a small criticism, it's that the documentation for the beta has been poor - particularly with respect to installation. I'm very glad to have found this thread, and I am very much looking forward to the official launch of 4.0. 

Is there an official date yet?

**Comment by Noviny** [comment] 2017-03-07 23:05
We haven't announced a date yet. Documentation is actually one of the blockers for launching, which we're trying to crunch through now.

**Comment by madhavinath** [comment] 2017-03-08 12:47
trying to trigger email..but getting  "The "keystone-email" package needs to be installed to send emails Error: The "keystone-email" package needs to be installed to send emails". any help??
