### ISSUE TITLE
Using default user and password won't allow login.

### ISSUE THREAD

**Issue by Argofanaticus** [keystonejs/generator-keystone#242] opened 2017-03-09 14:35 UTC
Hi, if I run the generator and leave the password to the default value I'm unable to log in.
Supplying a password causes the login to function correctly even if "admin" is re-entered.

**Comment by Noviny** [comment] 2017-03-10 02:05
Do you know what it ends up as in the database?

**Comment by Argofanaticus** [comment] 2017-03-10 15:19
Hi Ben, first off, very nice job on this project.
Hats off to you and the team.

Second, I feel like an idiot now.
Yesterday I managed to recreate the problem 3 times, you know to be sure.
Today I'm unable to reproduce it, PBKAC I guess.

Sorry for the hassle.
Marc.

**Comment by Noviny** [comment] 2017-03-12 13:29
All good, thanks for the nice words!

And all good on not being able to reproduce. I'm going to close this issue for now, but reopen it if it turns out to be a \*thing\*.

**Closed by Noviny** 2017-03-12 13:29 UTC
