### ISSUE TITLE
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.json'

### ISSUE THREAD

**Issue by morenoh149** [keystonejs/generator-keystone#118] opened 2015-08-05 19:49 UTC
from https://github.com/keystonejs/keystone/issues/1566

**Comment by yoshiokatsuneo** [comment] 2015-08-24 05:09
I got the error when I call the command on "root" account because yeoman change uid to "1000" on Linux...

**Comment by skate056** [comment] 2015-10-28 17:15
I get the same error. Is there any workaround for this?

**Comment by morenoh149** [comment] 2015-10-28 23:04
what platform are you all deploying to? The original thread author said he was using fedora.

**Comment by itsatony** [comment] 2015-11-02 16:37
same ubuntu 14.04

**Comment by codefolk** [comment] 2015-11-05 04:33
Facing this issue in ubuntu 14.04 LTS

**Comment by morenoh149** [comment] 2015-11-09 01:14
what steps are there to reproduce? just running the generator after install? Any other details to narrow things down please share.

**Comment by codefolk** [comment] 2015-11-11 07:49
when try to create angular project using yeoman generator after installing

**Comment by TinajaLabs** [comment] 2015-11-12 08:29
Me too.  Trying to install hubot after installing rocket.chat on ubuntu 14.04 droplet.

```/root/.config/configstore/insight-yo.json``` never gets created.

```
root@rocket:/opt/myhubot# yo hubot
/usr/lib/node_modules/yo/node_modules/configstore/index.js:53
                                throw err;
                                      ^
Error: EACCES, permission denied '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:130:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by morenoh149** [comment] 2015-11-13 20:25
From this https://www.digitalocean.com/community/questions/issue-with-yo-generator-on-mean-one-click-install-image looks like its a user permission issue on your servers. Possible soultion is to use nvm and run yeoman under that.

**Comment by pkrishanth** [comment] 2016-01-20 12:14
Same error on ubuntu 14.04 LTS VM  :(

**Comment by creynders** [comment] 2016-01-20 16:05
Some potential solution strategies. I'm closing this however, as it really has nothing to do with keystone nor its generator.

**Closed by creynders** 2016-01-20 16:05 UTC

**Comment by jimbojw** [comment] 2016-08-02 11:49
The root cause of this issue (and many like it) is https://github.com/npm/write-file-atomic/issues/11.

There is an outstanding patch which will fix this for everyone. We're all waiting for someone from npm to accept it: https://github.com/npm/write-file-atomic/pull/13

**Comment by phamdt** [comment] 2017-08-27 05:35
any updates?
