### ISSUE TITLE
Generator fails if new directory selected

### ISSUE THREAD

**Issue by internetErik** [keystonejs/generator-keystone#80] opened 2014-12-01 04:49 UTC
I just updated the generator, and now I get an error - not sure if it was there before my udpate.
Running the generator in window 8.1 in git bash.  

If I select Y for create new directory option, any answer I give for mandrill (next question) causes an exception to be thrown in console.  

The error seems to be in index.js on line 180 on a call to slugify.  I'll see if I have a sec to read through (was only testing the generator), but figured I would report it first.

Here is the error: 

```
C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:9048
                throw e;
                      ^
TypeError: Object function lodash(value) {
      // don't wrap if already wrapped, even if wrapped by a different `lodash` constructor
      return (value && typeof value == 'object' && !isArray(value) && hasOwnProperty.call(value, '__wrapped__'))
       ? value
       : new lodashWrapper(value);
    } has no method 'slugify'
    at KeystoneGenerator.<anonymous> (C:\Users\Erik\AppData\Roaming\npm\node_modules\generator-keystone\app\index.js:180:27)
    at PromptUI.onCompletion (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\lib\ui\prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1775:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1712:14)
    at AutoDetachObserverPrototype.completed (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:9068:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1712:14)
    at AnonymousObserver._onCompleted (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:2801:56)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1775:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1712:14)
    at AutoDetachObserverPrototype.completed (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:9068:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Erik\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1712:14)
```

**Comment by xres** [comment] 2015-01-08 06:14
I got the same error just now on a fresh Ubuntu 14.04 install. Answered Y to creating new directory and got the error pasted below, same result on the second try. On the third try, I answered N to new directory and it worked fine.

node v0.10.35
generator-keystone v0.2.15

```
/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9229
        throw e;
              ^
TypeError: Object function lodash(value) {
      // don't wrap if already wrapped, even if wrapped by a different `lodash` constructor
      return (value && typeof value == 'object' && !isArray(value) && hasOwnProperty.call(value, '__wrapped__'))
       ? value
       : new lodashWrapper(value);
    } has no method 'slugify'
    at KeystoneGenerator.<anonymous> (/usr/lib/node_modules/generator-keystone/app/index.js:180:27)
    at PromptUI.onCompletion (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1878:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1815:14)
    at AutoDetachObserverPrototype.completed (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9247:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1815:14)
    at AnonymousObserver._onCompleted (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:2921:56)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1878:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1815:14)
    at AutoDetachObserverPrototype.completed (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9247:23)
```

**Comment by JedWatson** [comment] 2015-01-08 23:45
This is *really* weird. That "breaks 1st, 2nd and work 3rd time" thing makes no sense.

Especially because `_.slugify` is used in multiple places around the generator, not just the new directory option.

Also, I can't reproduce it.

The offending line is:

```
if (this.newDirectory) {
	this.destinationRoot(_.slugify(this.projectName));
}
```

If anybody has any ideas or can debug it further, please let me know.

**Comment by JedWatson** [comment] 2015-01-08 23:50
Whoops - sorry, misread your comment @xres, answering "N" on the third time _totally_ makes sense. I'll pull in another package for slufigification and see if that fixes things, this is still breaking inconsistently.

**Comment by Noviny** [comment] 2017-02-17 03:39
Old bug, closing as we clean up the issue track.

Comment if you experience this.

**Closed** 2017-02-17 03:39 UTC
